[package]
name = "streams"
version = "0.1.0"
authors = ["gsmlg <me@gsmlg.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.1.17"
rand = "0.3.18"

